version: "3.4"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/minio/mimir && minio server --quiet /data/minio"]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data/minio

    command: ["sh", "-c", "mkdir -p /data/minio/loki && /usr/bin/docker-entrypoint.sh minio server /data/minio"]
    container_name: minio
    entrypoint: sh
    environment:
      MINIO_ACCESS_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SECRET_KEY: minio456
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s

    networks:
      loki: null
    ports:
    - published: 9000
      target: 9000
    restart: always
